version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: kiryana
      POSTGRES_PASSWORD: kiryana123
      POSTGRES_DB: kiryana
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://kiryana:kiryana123@db:5432/kiryana
      API_KEY_STORE1: store1_api_key
      API_KEY_STORE2: store2_api_key
      RATE_LIMIT_MINUTE: 100

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  postgres-data: